#!/bin/sh
PATTERN="BLIS [0-9][0-9]*[ -_]/w/w*"
master_branch="master"
develop_branch="develop"
current_branch="$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)"
if [ "$current_branch" = "$develop_branch" ]; then
	if test "" = "$(grep "$PATTERN" "$1")"; then
		echo "error"
		exit 1
	fi
		echo "all good"
fi
		echo "all good2"
exit 1